MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  # PRETRAIN_PATH: 'C:\Users\ziwang\.conda\jx_vit_base_p16_224-80ecf9dd.pth'
  PRETRAIN_PATH: '/mnt/data2/Hammad/git_repos/HTT-EXP/models/jx_vit_base_p16_224-80ecf9dd.pth'
  # CAPTION_MODEL_PATH: "/mnt/data2/Hammad/git_repos/Instruct-ReID/bert-base-uncased"
  CAPTION_MODEL_PATH: "/mnt/data2/Hammad/git_repos/HTT-EXP/models/nomic"
  METRIC_LOSS_TYPE: 'triplet'
  IF_LABELSMOOTH: 'off'
  IF_WITH_CENTER: 'no'
  NAME: 'transformer'
  NO_MARGIN: False
  # DEVICE_ID: ('4')
  TRANSFORMER_TYPE: 'vit_base_patch16_224_TransReID'
  STRIDE_SIZE: [16, 16]
  # TRAIN_MODE: 'RNT'
  ID_LOSS_WEIGHT: 0.5 
  TRIPLET_LOSS_WEIGHT: 2.0
  DISTILL:
    ENABLE: True
    W: 0.5          # λ_dist in the paper

INPUT:
  SIZE_TRAIN: [256, 128]
  SIZE_TEST: [256, 128]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  PADDING: 10
  PIXEL_MEAN: [0.5, 0.5, 0.5]
  PIXEL_STD: [0.5, 0.5, 0.5]

DATASETS:
  MULTI: False                 # False → use the single dataset in NAMES
  NAMES: [market1501]
  # NAMES: [msmt17]
  ROOT_DIR: ('/mnt/data2/Hammad/Datasets/ReID_data')

DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 4
  NUM_WORKERS: 16
  persistent_workers: True
  pin_memory: True
  prefetch_factor: 4

IMAGE_MODALITY: ["RGB", "IR", "TI"]

CAPTION:
  ENABLE: True
  STRATEGY: "rgb_only"   # or "rgb_only" / "matched"
  LOSS:
    INFO_NCE: True   # new switch
    TRIPLET: True
    ADAPTIVE_TRIPLET: True
    CONTRASTIVE: True
    WEIGHT: 1.0



TRAIN:
  ADAPTER_ONLY: True

SOLVER:
  OPTIMIZER_NAME: 'AdamW'
  MAX_EPOCHS: 90
  BASE_LR: 3e-5
  IMS_PER_BATCH: 64
  WARMUP_METHOD: 'linear'
  LARGE_FC_LR: False
  CHECKPOINT_PERIOD: 1
  LOG_PERIOD: 50
  EVAL_PERIOD: 1
  WEIGHT_DECAY:  0.05
  WEIGHT_DECAY_BIAS: 1e-4
  BIAS_LR_FACTOR: 2
  # SEED: 1

TTA:
  ENTROPY_ENABLE: True
  ENTROPY_W:      1.0


TEST:
  EVAL: True
  IMS_PER_BATCH: 256
  RE_RANKING: False
  # WEIGHT: 'E:\code\TransReID-3modal-ttt-main-AAAI2024\logs_rgbnt201\baseline+CIM15-68.5% 71.1% 82.7% 88.9%\transformer_best.pth'
  WEIGHT: ''
  # NECK_FEAT: 'after'
  NECK_FEAT: 'before'
  FEAT_NORM: 'yes'

OUTPUT_DIR: './logs/Market1501/4M-RGB-text-final-3'
# OUTPUT_DIR: './logs/MSMT/4M-RGB-text-final-1'
#now loss function adjusted